version: '3.8'

services:

    todo-ui:

        build:
            context: ./todo-ui
            dockerfile: Dockerfile.dev

        image: todo-ui-dev:0.1.0

        container_name: todo-ui-dev

        ports:
            - 4000:3000

        environment:
            HOST: 0.0.0.0
            PORT: 3000
            WDS_SOCKET_PORT: 4000

        # монтирование конфиг файла снаружи в конфиг файл внутри контейнера
        # в dev режиме это можно делать, при сборке так делать уже нельзя
        volumes:
            - ./config-todo-ui/config.js:/app/config/config.js:ro

    todo-kafka:

        environment:
            KAFKA_CFG_ZOOKEEPER_CONNECT: todo-zoo:2181
            KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
            KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
            KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
            ALLOW_PLAINTEXT_LISTENER: 'yes'
