version: '3.8'

services:

    todo-ui:

        # всегда стартует после падения или перезапуска системы
        restart: always

        build:
            context: ./todo-ui
            dockerfile: Dockerfile.prod

            # вместо environment и env_file
            # аргументы отсюда можно использовать в контейнере c node
            args:
                - ARG_FROM_DOCKER_COMPOSE=1613

        image: todo-ui:0.1.0

        container_name: todo-ui

        # стандартные порты для работы с http и https 
        ports:
            - 80:80
            - 443:443

        env_file:
            - environment.env

        # монтирование файла конфигурации nginx
        # монтирование директории с конфигурацией доступных сайтов
        volumes:
            - ./config-nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./config-nginx-sites-available/:/etc/nginx/sites-available/:ro

            - ./certs/certbot/conf/:/etc/letsencrypt:ro
            - ./certs/certbot/www/:/var/www/certbot:ro

    todo-backend:

        restart: always

    notifier:

        restart: always

    todo-kafka:

        environment:
            KAFKA_CFG_ZOOKEEPER_CONNECT: todo-zoo:2181
            KAFKA_CFG_LISTENERS: PLAINTEXT://todo-kafka:9092
            KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://todo-kafka:9092
            KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
            ALLOW_PLAINTEXT_LISTENER: 'yes'

    # для создания SSL сертификтов в letsencrypt
    certbot:

        image: certbot/certbot

        container_name: certbot

        volumes:
            - ./certs/certbot/conf/:/etc/letsencrypt:rw
            - ./certs/certbot/www/:/var/www/certbot:rw

        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
