version: '3.8'

services:

    todo-ui:

        build:
            context: ./todo-ui
            dockerfile: Dockerfile.prod

            # вместо environment и env_file
            # аргументы отсюда можно использовать в контейнере c node
            args:
                - ARG_FROM_DOCKER_COMPOSE=1613

        image: todo-ui:0.1.0

        container_name: todo-ui

        # стандартные порты для работы с http и https 
        ports:
            - 8080:80
            - 4433:443

        # монтирование файла конфигурации nginx
        # монтирование директории с конфигурацией доступных сайтов
        volumes:
            - ./config-nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./config-nginx-sites-available/:/etc/nginx/sites-available/:ro
