#!/bin/bash

set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $TODO_BACKEND_DB_USER WITH LOGIN SUPERUSER PASSWORD '$TODO_BACKEND_DB_USER_PASSWORD';
    CREATE DATABASE $TODO_BACKEND_DB WITH OWNER $TODO_BACKEND_DB_USER;
    GRANT ALL PRIVILEGES ON DATABASE $TODO_BACKEND_DB TO $TODO_BACKEND_DB_USER;

    CREATE USER $NOTIFIER_DB_USER WITH LOGIN SUPERUSER PASSWORD '$NOTIFIER_DB_USER_PASSWORD';
    CREATE DATABASE $NOTIFIER_DB WITH OWNER $NOTIFIER_DB_USER;
    GRANT ALL PRIVILEGES ON DATABASE $NOTIFIER_DB TO $NOTIFIER_DB_USER;
EOSQL
